const sourceState = { filter: "全部", query: "", view: "shortcut", registry: null, reviewLog: null };
const escapeHTML = (value = "") => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const allowedHttpHosts = new Set(["bm.scs.gov.cn", "subb.scs.gov.cn", "job.mohrss.gov.cn", "wap.sasac.gov.cn", "www.spacetalent.com.cn"]);
const safeUrl = (value = "") => { try { const url = new URL(value); return url.protocol === "https:" || (url.protocol === "http:" && allowedHttpHosts.has(url.hostname)) ? url.href : "#"; } catch { return "#"; } };
const formatDateTime = (value) => value ? new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)).replaceAll("/", ".") : "未记录";
const roleLabels = { authoritative: "官方发布依据", roster: "官方名录", discovery: "发现线索" };
function statusPresentation(status) { if (!status || status.startsWith("checked")) return { label: "已完成核验", className: "checked" }; if (status === "accessible-incomplete") return { label: "本轮未完成", className: "incomplete" }; if (status === "temporarily-unavailable" || status === "semantic-404") return { label: "等待更新", className: "waiting" }; return { label: "待继续核验", className: "waiting" }; }
function latestChecks() { const checks = new Map(); for (const run of sourceState.reviewLog.runs || []) for (const check of run.sourceChecks || []) if (!checks.has(check.sourceId)) checks.set(check.sourceId, check); return checks; }
function collectionStatus(check) { if (!check) return { label: "尚未写入核验记录", className: "waiting" }; if (check.checkedAt !== sourceState.reviewLog.meta.lastRunAt) return { label: "未在最近更新中", className: "waiting" }; return statusPresentation(check.status); }
function collectionEntry(source, check) { return check?.accessEvidence?.[0]?.requestedUrl || source.collectionEntryUrl || source.entryUrl; }
function collectionMethod(source) { const mode = source.collectionAccessMode || source.accessMode || ""; if (mode.startsWith("script-")) return "脚本采集与核验"; if (mode.includes("filter")) return "站内筛选与核验"; if (mode.startsWith("browser-")) return "浏览器核验"; return "公告与职位信息核验"; }
function filteredSources() { const keyword = sourceState.query.trim().toLowerCase(); return sourceState.registry.sources.filter((source) => { const coverage = source.coverage || []; const matchesFilter = sourceState.filter === "全部" || coverage.includes(sourceState.filter); const haystack = [source.organization, source.type, ...coverage, ...(source.domains || [])].join(" ").toLowerCase(); return matchesFilter && (!keyword || haystack.includes(keyword)); }); }
function tagsFor(source) { const coverage = (source.coverage || []).filter((item) => item !== "发现线索"); return coverage.map((item) => `<span>${escapeHTML(item)}</span>`).join("") || "<span>综合信息</span>"; }
function shortcutCard(source) { return `<article class="source-directory-card source-shortcut role-${escapeHTML(source.role)}"><div class="source-card-topline"><span class="source-purpose">用户快捷入口</span><span class="source-role">${escapeHTML(roleLabels[source.role] || source.type)}</span></div><h3>${escapeHTML(source.organization)}</h3><p class="source-type">${escapeHTML(source.type)} · 供直接进入官方页面</p><div class="source-coverage"><strong>覆盖</strong>${tagsFor(source)}</div><div class="source-card-footer"><span>不显示采集状态</span><a href="${safeUrl(source.entryUrl)}" target="_blank" rel="noreferrer">打开官网 ↗</a></div></article>`; }
function collectionCard(source, check) { const status = collectionStatus(check); const checkedAt = check?.checkedAt ? `最近核验 ${formatDateTime(check.checkedAt)}` : "尚未写入核验记录"; return `<article class="source-directory-card source-collection role-${escapeHTML(source.role)}"><div class="source-card-topline"><span class="source-purpose">采集与核验路线</span><span class="source-health ${status.className}">${status.label}</span></div><h3>${escapeHTML(source.organization)}</h3><p class="source-type">${escapeHTML(collectionMethod(source))} · ${escapeHTML(roleLabels[source.role] || source.type)}</p><div class="source-coverage"><strong>覆盖</strong>${tagsFor(source)}</div><div class="source-card-footer"><span>${escapeHTML(checkedAt)}</span><a href="${safeUrl(collectionEntry(source, check))}" target="_blank" rel="noreferrer">查看采集入口 ↗</a></div></article>`; }
function updateDirectoryCopy() { const shortcut = sourceState.view === "shortcut"; document.querySelector("#source-directory-kicker").textContent = shortcut ? "给你打开的网站" : "后台实际使用的来源"; document.querySelector("#source-directory-title").textContent = shortcut ? "官方快捷入口" : "采集与核验路线"; document.querySelector("#source-directory-description").textContent = shortcut ? "这里仅用于直接进入官方页面；不显示采集成功、失败或待确认状态。" : "这里展示后台实际访问的入口、核验方式和最近一次执行状态；不会替代岗位页的官方链接。"; }
function renderSources() { const grid = document.querySelector("#source-grid"); const resultCount = document.querySelector("#source-result-count"); const checks = latestChecks(); const sources = filteredSources(); resultCount.textContent = `${sources.length} 个${sourceState.view === "shortcut" ? "快捷入口" : "采集路线"}`; updateDirectoryCopy(); if (!sources.length) { grid.innerHTML = '<div class="empty-state"><strong>没有找到对应的信息源</strong><p>换一个分类或关键词试试。</p></div>'; return; } grid.innerHTML = sources.map((source) => sourceState.view === "shortcut" ? shortcutCard(source) : collectionCard(source, checks.get(source.id))).join(""); }
function bindSourceFilters() { document.querySelectorAll("[data-source-filter]").forEach((button) => button.addEventListener("click", () => { sourceState.filter = button.dataset.sourceFilter; document.querySelectorAll("[data-source-filter]").forEach((item) => item.classList.toggle("active", item === button)); renderSources(); })); document.querySelector("#source-search").addEventListener("input", (event) => { sourceState.query = event.target.value; renderSources(); }); }
function bindSourceViews() { document.querySelectorAll("[data-source-view]").forEach((button) => button.addEventListener("click", () => { sourceState.view = button.dataset.sourceView; document.querySelectorAll("[data-source-view]").forEach((item) => { const active = item === button; item.classList.toggle("active", active); item.setAttribute("aria-selected", String(active)); }); renderSources(); })); }
async function initSources() { try { const [registryResponse, reviewResponse] = await Promise.all([fetch("data/source-registry.json", { cache: "no-store" }), fetch("data/review-log.json", { cache: "no-store" })]); if (!registryResponse.ok || !reviewResponse.ok) throw new Error("信息源数据读取失败"); [sourceState.registry, sourceState.reviewLog] = await Promise.all([registryResponse.json(), reviewResponse.json()]); document.querySelector("#sync-date").innerHTML = sourceState.reviewLog.meta.initializationStatus === "awaiting-first-sync" ? `<i></i>等待首次完整更新` : `<i></i>最近更新：${formatDateTime(sourceState.reviewLog.meta.lastRunAt)}`; bindSourceFilters(); bindSourceViews(); renderSources(); } catch (error) { document.querySelector("#source-grid").innerHTML = '<div class="empty-state"><strong>信息源暂时没有加载出来</strong><p>请稍后刷新页面。</p></div>'; console.error("Failed to load sources", error); } }
initSources();
